version: '3'

services:
  docker:
    image: 20102172/aplicacion-img
    environment:
      - SERVER_PORT=80
    networks:
      - red-docker
    ports:
      - 82:80
    depends_on:
      - encuesta

  docker1:
    image: 20102172/aplicacion-img
    environment:
      - SERVER_PORT=80
    networks:
      - red-docker
    ports:
      - 83:80
    depends_on:
      - encuesta

  docker2:
    image: 20102172/aplicacion-img
    environment:
      - SERVER_PORT=80
    networks:
      - red-docker
    ports:
      - 84:80
    depends_on:
      - encuesta

  encuesta:
    image: mysql:8
    networks:
      - red-docker
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=encuesta
    volumes:
      - mysql_db:/var/lib/mysql

  ha-proxy:
    image: 20102172/haproxy-config
    networks:
      - red-docker
    depends_on:
      - docker
      - docker1
      - docker2
    volumes:
      - /usr/local/etc/haproxy
    ports:
      - 81:80

volumes:
  mysql_db:

networks:
  red-docker: